---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

params:
  UPDATING_OPS_FILE: false
  FILE_TO_UPDATE: ~
  UPDATING_SOURCE_RELEASE: false
  SOURCE_RELEASE_FILE: ~

inputs:
  - name: bosh-deployment
  - name: compiled-release

outputs:
  - name: bosh-deployment
    path: bosh-deployment-output

run:
  path: bosh-deployment/ci/tasks/update-release.sh
