---
groups:
  - name: bosh-deployment
    jobs:
    - test-bosh-lite-gcp
    - test-smoke
    - promote

jobs:
  - name: test-bosh-lite-gcp
    serial: true
    build_logs_to_retain: 250
    plan:
      - get: bosh-deployment
        trigger: true
      - task: test-bosh-lite-gcp
        file: bosh-deployment/ci/tasks/test-bosh-lite-gcp.yml
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp_service_account_json))
          BBL_GCP_REGION: us-west1

  - name: test-smoke
    serial: true
    build_logs_to_retain: 250
    plan:
      - get: bosh-deployment
        trigger: true
      - task: test-smoke
        file: bosh-deployment/ci/tasks/test-smoke.yml

  - name: promote
    serial: true
    build_logs_to_retain: 250
    plan:
    - get: bosh-deployment
      trigger: true
      passed:
      - test-smoke
      - test-bosh-lite-gcp
    - put: bosh-deployment-master
      params:
        repository: bosh-deployment
        rebase: true

resources:
- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: develop

- name: bosh-deployment-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-deployment
    branch: master
    private_key: ((bosh_deployment_deploy_key))
